server:
  port: 8180
  address: 47.95.214.100
#添加数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.52.207.164:3306/quant?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Sjh13693094831
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 6000
      time-between-eviction-runs-millis: 3000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      use-global-data-source-stat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: qt-admin
  redis:
    database: 0
    host: 47.52.207.164
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 15000
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: yangge975965279@vip.qq.com #QQ邮箱
    password: sdncjthvgtwrbfgg #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: quant #可以任意
    properties.mail.display.sendname: quant Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: yangge975965279@vip.qq.com #与上面的username保持一致
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:47.95.214.100}:${EUREKA_ZONE_PORT:8762}/eureka/
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml

vpnproxy:
  enable: true
  ip: 127.0.0.1
  port: 1080